In [37]:
import pandas as pd

df = pd.read_csv("Indian_Food_Nutrition_Processed.csv")
print(df.head(1))

              Dish Name  Calories (kcal)  Carbohydrates (g)  Protein (g)  \
0  Hot tea (Garam Chai)            16.14               2.58         0.39

   Fats (g)  Free Sugar (g)  Fibre (g)  Sodium (mg)  Calcium (mg)  Iron (mg)  \
0      0.53            2.58        0.0         3.12          14.2       0.02

   Vitamin C (mg)  Folate (µg)
0             0.5          1.8

In [38]:
print(df.isnull().sum())

Dish Name             0
Calories (kcal)       0
Carbohydrates (g)     0
Protein (g)           0
Fats (g)              0
Free Sugar (g)        0
Fibre (g)             0
Sodium (mg)           0
Calcium (mg)          0
Iron (mg)             0
Vitamin C (mg)       82
Folate (µg)          82
dtype: int64

In [39]:
df = df.dropna()
print(df.head(1))

              Dish Name  Calories (kcal)  Carbohydrates (g)  Protein (g)  \
0  Hot tea (Garam Chai)            16.14               2.58         0.39

   Fats (g)  Free Sugar (g)  Fibre (g)  Sodium (mg)  Calcium (mg)  Iron (mg)  \
0      0.53            2.58        0.0         3.12          14.2       0.02

   Vitamin C (mg)  Folate (µg)
0             0.5          1.8

In [43]:
print(df.columns)

Index(['Dish Name', 'Calories (kcal)', 'Carbohydrates (g)', 'Protein (g)',
       'Fats (g)', 'Fibre (g)', 'Calcium (mg)', 'Iron (mg)', 'Vitamin C (mg)',
       'Folate (µg)'],
      dtype='str')

In [49]:
# df = df.drop(["Free Sugar (g)", "Sodium (mg)"], axis=1)
df.head(2)

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Fibre (g),Calcium (mg),Iron (mg),Vitamin C (mg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,0.0,14.20,0.02,0.50
1,Instant coffee,23.16,3.65,0.64,0.75,0.0,20.87,0.06,1.51

In [50]:
df

,Dish Name,Calories (kcal),Carbohydrates (g),Protein (g),Fats (g),Fibre (g),Calcium (mg),Iron (mg),Vitamin C (mg)
0,Hot tea (Garam Chai),16.14,2.58,0.39,0.53,0.00,14.20,0.02,0.50
1,Instant coffee,23.16,3.65,0.64,0.75,0.00,20.87,0.06,1.51
2,Espreso coffee,51.54,6.62,1.75,2.14,0.00,58.10,0.15,1.51
3,Iced tea,10.34,2.70,0.03,0.01,0.00,1.18,0.02,5.95
4,Raw mango drink (Aam panna),35.92,9.05,0.16,0.03,0.61,7.08,0.14,45.30
...,...,...,...,...,...,...,...,...,...
927,Bread roll,435.46,16.12,2.85,40.25,1.45,44.83,0.71,6.79
928,Soya seekh kebab,115.05,10.00,5.40,5.88,2.24,15.67,1.26,8.56
929,Classic seasoned black beans,28.78,7.66,8.01,8.28,3.51,40.11,1.90,8.54
930,Maa chaane ki dal,344.67,43.11,19.80,9.50,13.45,68.65,5.97,1.43
931,Garlic chickpea soup (Lahasun aur chane ka sho...,89.53,13.92,4.45,2.01,2.84,13.93,0.96,13.24

In [51]:
df.to_csv("clean_data.csv", index=False)